Repository hmcts/hwf-staffapp, pull requests merged in 2023-12, with the labels that each got.

#1559 RST-6098 Fixing issue with nil savings
  app/lib/band_calculation_income.rb
  spec/lib/band_base_calculation_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1559

#1565 RST-6113 Fixing nil issue
  app/models/views/overview/application.rb
  spec/models/views/overview/application_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1565

#1567 RST-6114 - Fixing display logic
  app/models/views/overview/application.rb
  spec/models/views/overview/application_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1567

#1571 Rst 6078a
  app/models/forms/application/partner.rb
  spec/models/forms/application/partner_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1571

#1573 RST-5995 mi report
  app/models/forms/application/detail.rb
  app/models/views/reports/hmrc_ocmc_data_export.rb
  app/models/views/reports/ocmc_data_export.rb
  app/models/views/reports/ocmc_export_helper.rb
  app/models/views/reports/raw_data_export.rb
  spec/factories/applications.rb
  spec/factories/details.rb
  spec/models/forms/application/detail_spec.rb
  spec/models/views/reports/hmrc_ocmc_data_export_spec.rb
  spec/models/views/reports/ocmc_data_export_spec.rb
  spec/models/views/reports/raw_data_export_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1573

#1574 RST-6125 income period
  app/builders/application_builder.rb
  app/models/views/overview/application.rb
  app/views/evidence/show.html.slim
  app/views/online_applications/show.html.slim
  app/views/part_payments/show.html.slim
  app/views/shared/part_payment_evidence/_summary.html.slim
  app/views/shared/processed_and_deleted/_show.html.slim
  config/locales/en.yml
  spec/builders/application_builder_spec.rb
  spec/models/views/overview/application_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1574

#1575 Deploy test
  charts/help-with-fees-staffapp/Chart.yaml
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1575
