Repository hmcts/hwf-staffapp, pull requests merged in 2023-11, with the labels that each got.

#1533 Revert "RST-5637-v2 UCD content change"
  config/locales/emails_en.yml
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1533

#1537 RST-5256 band integration v3
  app/controllers/api/submissions_controller.rb
  app/controllers/online_applications_controller.rb
  app/helpers/section_views_helper.rb
  app/lib/band_base_calculation.rb
  app/lib/band_calculation_helper.rb
  app/lib/band_calculation_income.rb
  app/models/online_application.rb
  app/models/views/overview/children.rb
  app/models/views/overview/online_applicant.rb
  app/services/process_application.rb
  app/views/online_applications/show.html.slim
  config/locales/en.yml
  db/migrate/20231121134436_add_new_fields_to_online_application.rb
  db/schema.rb
  spec/controllers/applications/process/incomes_controller_spec.rb
  spec/controllers/online_applications_controller_spec.rb
  spec/lib/band_base_calculation_spec.rb
  spec/models/views/overview/online_applicant_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1537

#1538 RST-5447 - Fixing minor issues
  app/views/applications/process/summary/_post_ucd.html.slim
  app/views/applications/process/summary/_pre_ucd.html.slim
  app/views/applications/process/summary/index.html.slim
  config/locales/en.yml
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1538

#1542 RST-5896 average income no HMRC check
  app/controllers/applications/process/confirmation_controller.rb
  app/helpers/home_helper.rb
  spec/controllers/applications/process/confirmation_controller_spec.rb
  spec/helpers/home_helper_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1542

#1539 RST-6008 Added UCD content
  app/views/applications/process/declaration/index.html.slim
  app/views/applications/process/details/index.html.slim
  app/views/applications/process/fee_status/index.html.slim
  app/views/applications/process/income_kind_applicants/index.html.slim
  app/views/applications/process/income_kind_partners/index.html.slim
  app/views/applications/process/incomes/index.html.slim
  app/views/applications/process/personal_informations/index.html.slim
  app/views/applications/process/representative/index.html.slim
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1539

#1544 RST-6061 saving fails flow
  app/controllers/applications/process/savings_investments_controller.rb
  app/views/applications/process/summary/_post_ucd.html.slim
  spec/controllers/applications/process/savings_investments_controller_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1544

#1545 RST-6062 age cap
  app/builders/application_builder.rb
  app/controllers/api/submissions_controller.rb
  app/helpers/home_helper.rb
  app/lib/band_base_calculation.rb
  app/lib/band_calculation_helper.rb
  app/models/online_application.rb
  app/models/saving.rb
  app/models/views/overview/representative.rb
  app/views/online_applications/show.html.slim
  db/migrate/20231123223101_add_income_period_to_online_applicaiton.rb
  db/migrate/20231123223304_add_over_16_to_applicant.rb
  db/migrate/20231124101322_remove_not_null_on_representative.rb
  db/schema.rb
  spec/builders/application_builder_spec.rb
  spec/factories/online_applications.rb
  spec/features/online_applications/evidence_check_spec.rb
  spec/lib/band_base_calculation_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1545

#1543 RST-6028 Added content
  app/models/views/confirmation/result.rb
  app/models/views/overview/representative.rb
  app/views/applications/process/confirmation/index.html.slim
  app/views/evidence/return_letter.html.slim
  app/views/evidence_checks/show.html.slim
  app/views/part_payments/_failed_letter.html.slim
  app/views/part_payments/return_letter.html.slim
  app/views/reports/letters.html.slim
  app/views/reports/new_letters.html.slim
  app/views/shared/_refund_template.html.slim
  config/locales/letters_en.yml
  features/step_definitions/return_letter_steps.rb
  spec/features/evidence-checks/evidence_check_page_displays_letter_to_be_sent_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1543

#1536 RST-5447 summary
  README.md
  app/models/applicant.rb
  app/models/views/overview/savings_and_investments.rb
  spec/models/applicant_spec.rb
  spec/models/views/overview/savings_and_investments_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1536

#1550 Updating validation
  app/controllers/api/submissions_controller.rb
  app/models/online_application.rb
  spec/models/online_application_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1550

#1554 RST-6078 Removed validation for partner dob and name
  app/models/forms/application/partner.rb
  features/step_definitions/staff_guides_steps.rb
  spec/models/forms/application/partner_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1554
