Repository hmcts/hwf-staffapp, pull requests merged in 2024-11, with the labels that each got.

#1897 RST-6822 - fix admin completed application search bar
  README.md
  app/policies/application_policy.rb
  app/views/home/index.html.slim
  db/schema.rb
  spec/policies/application_policy_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1897

#1900 RST-6928 HMRC rollout
  Dockerfile
  app/controllers/report/ocmc_controller.rb
  app/models/concerns/application_checkable.rb
  app/models/views/reports/ocmc_data_export.rb
  features/skip_ev_check_for_15_and_under.feature
  features/step_definitions/nino_evidence_steps.rb
  spec/controllers/report/ocmc_controller_spec.rb
  spec/factories/online_applications.rb
  spec/features/evidence-checks/evidence_check_spec.rb
  spec/features/no_evidence_check/rst_1006_spec.rb
  spec/features/no_evidence_check/rst_985_spec.rb
  spec/features/no_evidence_check/rst_987_spec.rb
  spec/features/no_evidence_check/skip_ev_check_for_15_and_under_spec.rb
  spec/features/online_applications/evidence_check_spec.rb
  spec/models/concerns/application_checkable_spec.rb
  spec/models/views/reports/ocmc_data_export_spec.rb
  spec/support/admin_application_steps.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1900

#1903 Remove claim_type and form_type fields
  db/schema.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1903

#1904 RST-6933 - Added decision date column
  Gemfile
  Gemfile.lock
  app/models/views/reports/raw_data_export.rb
  spec/models/views/reports/raw_data_export_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1904

#1908 Minor gem and rails update
  Gemfile
  Gemfile.lock
  charts/help-with-fees-staffapp/Chart.yaml
  features/support/download_helper.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1908

#1844 RST-6853 Error message in 'Waiting for Evidence' in staging environment
  app/models/views/application_list.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1844

#1916 RST-6990 - Fixing issue when no request data
  app/models/hmrc_check.rb
  lib/hmrc_missing_data.rb
  spec/models/hmrc_check_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1916

#1895 GovUK update to 5.7.1
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1895

#1917 Assets compile change
  config/environments/production.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1917

#1918 Revert "GovUK update to 5.7.1"
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1918

#1911 RST-6913 Added dropdown select for deleting applications
  app/controllers/processed_applications_controller.rb
  app/models/forms/application/delete.rb
  app/models/views/processed_data.rb
  app/models/views/reports/hmrc_ocmc_data_export.rb
  app/services/resolver_service.rb
  app/views/processed_applications/show.html.slim
  config/locales/en.yml
  db/migrate/20241108102655_add_deleted_reasons_list_to_applications.rb
  db/schema.rb
  features/processed_applications.feature
  features/step_definitions/processed_applications_steps.rb
  features/support/page_objects/processed_application_instance_page.rb
  spec/factories/applications.rb
  spec/features/processed_applications/delete_processed_application_spec.rb
  spec/features/processed_applications/list_deleted_applications_spec.rb
  spec/models/forms/application/delete_spec.rb
  spec/models/views/processed_data_spec.rb
  spec/services/resolver_service_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1911

#1922 Gem and Ruby update
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1922

#1921 RSt-6961 - Removing js compiler
  config/environments/production.rb
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1921

#1925 RST-6994 - Updated staff guides with new links
  app/helpers/guide_helper.rb
  app/views/guide/index.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
  features/staff_guides.feature
  features/step_definitions/process_online_application_steps.rb
  features/step_definitions/staff_guides_steps.rb
  features/support/page_objects/guide_page.rb
  spec/helpers/guide_helper_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1925

#1932 Debugging failing tests
  Jenkinsfile_CNP
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1932

#1936 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1936
