Repository hmcts/hwf-staffapp, pull requests merged in 2024-05, with the labels that each got.

#1702 RST-6593 - Updating benefit per child amount
  config/settings.yml
  spec/models/forms/evidence/hmrc_check_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1702

#1704 System/removing duplication sonar v1
  Gemfile
  Gemfile.lock
  app/builders/finance_transactional_report_builder.rb
  app/builders/report_base.rb
  app/models/views/reports/applicants_per_fy_export.rb
  app/models/views/reports/raw_data_export.rb
  spec/builders/report_base_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1704

#1705 Limit number of new password request attempts in one minute time period
  Jenkinsfile_CNP
  app/controllers/users/passwords_controller.rb
  charts/help-with-fees-staffapp/Chart.yaml
  config/locales/devise.en.yml
  db/migrate/20240430152321_add_last_password_reset_check_at_to_users.rb
  db/schema.rb
  spec/controllers/users/passwords_controller_spec.rb
  spec/features/new_password_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1705

#1709 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1709

#1710 RST-6033 - Loading redis url from keystore
  charts/help-with-fees-staffapp/Chart.yaml
  charts/help-with-fees-staffapp/values.yaml
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1710

#1712 RST-6589 - Confirmation emails is now send to new address
  app/mailers/notify_mailer.rb
  spec/mailers/notify_mailer_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1712

#1708 RST-6155 - show legal representative details on online application check details…
  README.md
  app/controllers/online_applications_controller.rb
  app/helpers/section_views_helper.rb
  app/views/online_applications/show.html.slim
  spec/features/online_applications/evidence_check_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1708

#1706 RST-6033 navigation link
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/application_controller.rb
  app/controllers/applications/process/confirmation_controller.rb
  app/controllers/applications/process_controller.rb
  app/controllers/evidence_controller.rb
  app/controllers/home_controller.rb
  app/controllers/part_payments_controller.rb
  app/helpers/application_helper.rb
  app/lib/path_storage.rb
  app/views/layouts/application.html.slim
  app/views/layouts/local-template.html.erb
  charts/help-with-fees-staffapp/Chart.yaml
  config/settings.yml
  features/support/env.rb
  spec/lib/path_storage_spec.rb
  spec/rails_helper.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1706

#1713 Updating readme for the feature switch.
  README.md
  charts/help-with-fees-staffapp/Chart.yaml
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1713

#1717 RST-6643 - fix assigning representative for instance of Application
  app/helpers/section_views_helper.rb
  spec/controllers/evidence_controller_spec.rb
  spec/controllers/online_applications_controller_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1717

#1719 RST-6643 Disabling back link for now
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1719

#1716 RST-6630 - update crown logo
  app/views/layouts/local-template.html.erb
  public/favicon.ico
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1716

#1721 update nokogiri to 1.16.5
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1721

#1720 RST-5659 date received
  app/models/forms/online_application.rb
  app/models/validators/date_received_validator.rb
  config/locales/en.yml
  features/support/page_objects/process_online_application_page.rb
  spec/factories/online_applications.rb
  spec/features/applications/processing_refund_application_spec.rb
  spec/features/online_applications/evidence_check_spec.rb
  spec/features/online_applications/staff_can_add_details_spec.rb
  spec/models/forms/online_application_spec.rb
  spec/support/shared_examples/date_received_validation.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1720

#1725 RST-6657 - Adding Sentry reporting for Redis link
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
  app/lib/path_storage.rb
  spec/lib/path_storage_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1725

#1718 RST-6227 Savings and investments amount to be blank when savings are …
  app/models/views/reports/raw_data_export.rb
  charts/help-with-fees-staffapp/Chart.yaml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1718

#1728 RST-6638 - Updating additional income calculation
  app/models/forms/evidence/hmrc_check.rb
  charts/help-with-fees-staffapp/Chart.yaml
  config/settings.yml
  spec/models/forms/evidence/hmrc_check_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1728

#1731 RST-6219 feature test update
  .env.test
  features/step_definitions/ho_evidence_check_steps.rb
  features/step_definitions/summary_steps.rb
  features/step_definitions/unprocessed_applications_when_dwp_is_down_steps.rb
  features/support/page_objects/personal_details_page.rb
  spec/models/forms/application/fee_status_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1731

#1732 System gem updates
  .rubocop.yml
  Gemfile.lock
  app/models/forms/online_application.rb
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1732

#1733 RST-6224 - Replacing sass-rails with dart sass
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1733

#1734 Minor gem and accessible-autocomplete update
  Gemfile
  Gemfile.lock
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1734
