Repository hmcts/hwf-staffapp, pull requests merged in 2024-03, with the labels that each got.

#1638 RST-6102 Autofill and content of templates for income type and childr…
  app/helpers/income_type_helper.rb
  app/views/applications/process/confirmation/index.html.slim
  app/views/reports/new_letters.html.slim
  app/views/shared/_refund_template.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
  config/locales/letters_en.yml
  config/locales/new_letters_en.yml
  features/support/page_objects/confirmation_page.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1638

#1622 RST-6168 - Change capital column name and update capital bands
  app/models/views/reports/ocmc_data_export.rb
  app/models/views/reports/raw_data_export.rb
  spec/models/views/reports/ocmc_data_export_spec.rb
  spec/models/views/reports/raw_data_export_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1622

#1652 RST-6398 Updating failing feature tests
  app/views/benefit_overrides/paper_evidence.html.slim
  features/step_definitions/override_steps.rb
  features/step_definitions/process_online_application_steps.rb
  features/step_definitions/staff_steps.rb
  features/support/page_objects/confirmation_page.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1652

#1653 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1653

#1662 Security fix for rotp gem
  Gemfile
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1662

#1664 RST-6109 position in the organisation
  app/builders/application_builder.rb
  app/controllers/api/submissions_controller.rb
  app/models/views/overview/representative.rb
  charts/help-with-fees-staffapp/Chart.yaml
  charts/help-with-fees-staffapp/values.yaml
  config/locales/en.yml
  db/migrate/20240319133300_add_legal_representative_position_to_online_application_table.rb
  db/migrate/20240319134944_add_position_to_representative.rb
  db/schema.rb
  spec/builders/application_builder_spec.rb
  spec/factories/online_applications.rb
  spec/factories/representatives.rb
  spec/models/views/overview/representative_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1664

#1665 RST-6427 under 16
  app/models/applicant.rb
  app/models/views/overview/applicant.rb
  app/models/views/overview/online_applicant.rb
  config/locales/en.yml
  features/skip_ev_check_for_15_and_under.feature
  features/step_definitions/skip_ev_check_for_15_and_under.steps.rb
  features/step_definitions/summary_steps.rb
  spec/models/views/overview/applicant_spec.rb
  spec/models/views/overview/online_applicant_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1665

#1655 RST-6253 - Whole functional test run
  charts/help-with-fees-staffapp/Chart.yaml
  features/step_definitions/staff_steps.rb
  lib/tasks/test.rake
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1655

#1666 RST-6344 Ruby version 3 - v2
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1666

#1650 RST-6380 - remove probate date validation
  app/models/forms/application/detail.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1650

#1672 Minor gem updates and Helm update
  Dockerfile
  Gemfile.lock
  charts/help-with-fees-staffapp/Chart.yaml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1672
