Repository hmcts/hwf-staffapp, pull requests merged in 2024-08, with the labels that each got.

#1801 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1801

#1803 RST-6806 Minor update to gov uk library
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1803

#1798 RST-6765 Banner change for processed evidence
  Gemfile.lock
  app/models/views/application_result.rb
  app/views/shared/_remission_type.html.slim
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1798

#1815 RST-6814 rails ang govuk updates
  .rubocop.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  app/helpers/evidence_check_helper.rb
  app/lib/log_stuff.rb
  app/models/application.rb
  app/models/evidence_check.rb
  app/models/forms/application/applicant.rb
  app/models/forms/application/partner.rb
  app/models/hmrc_call.rb
  app/models/hmrc_check.rb
  app/models/online_application.rb
  app/models/user.rb
  bin/brakeman
  bin/rubocop
  bin/setup
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/puma.rb
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1815

#1820 RST-6768 Add validation for duplicate ni number for applicant and partner
  Gemfile.lock
  app/models/forms/application/partner.rb
  app/views/applications/process/partner_informations/index.html.slim
  config/locales/en.yml
  spec/models/forms/application/partner_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1820

#1823 Minor gem updates
  .gitignore
  Gemfile.lock
  README.md
  app/models/applicant.rb
  app/models/views/overview/online_applicant.rb
  config/application.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1823
