Repository hmcts/hwf-staffapp, pull requests merged in 2024-09, with the labels that each got.

#1810 RST-6801 Part payment date from 14 to 28 days
  app/models/application.rb
  config/settings.yml
  spec/models/views/confirmation/result_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1810

#1838 System/ruby downgrade
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1838

#1827 RST-6830 Content on Application Details updated
  Gemfile
  Gemfile.lock
  app/views/applications/process/details/index.html.slim
  app/views/applications/process/fee_status/index.html.slim
  app/views/online_applications/edit.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1827

#1834 RST-6827 Wording fixed on decision page for non-representative cases
  app/helpers/greeting_helper.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1834

#1842 RST-6864 HMRC only with partner data
  .gitignore
  .rubocop.yml
  README.md
  app/controllers/applications/process/confirmation_controller.rb
  app/controllers/evidence/hmrc_controller.rb
  app/helpers/flash_message_helper.rb
  app/helpers/hmrc_check_helper.rb
  app/helpers/home_helper.rb
  app/lib/hmrc_income_parser.rb
  app/models/application.rb
  app/models/concerns/application_checkable.rb
  app/models/evidence_check.rb
  app/models/forms/evidence/hmrc_check.rb
  app/models/hmrc_check.rb
  app/models/views/overview/application.rb
  app/models/views/overview/hmrc_helper.rb
  app/models/views/overview/overview_helper.rb
  app/services/completed_application_redirect.rb
  app/services/concerns/hmrc_person_loadable.rb
  app/services/concerns/hmrc_tokenable.rb
  app/services/evidence_check_selector.rb
  app/services/hmrc_api_service.rb
  app/services/hmrc_service.rb
  app/views/applications/process/incomes/index.html.slim
  app/views/evidence/hmrc/show.html.slim
  app/views/evidence/hmrc_summary/show.html.slim
  config/locales/en.yml
  db/migrate/20240417100153_add_check_type_to_hmrc_checks.rb
  db/schema.rb
  lib/hmrc_frequency_helper.rb
  spec/controllers/applications/process/confirmation_controller_spec.rb
  spec/controllers/evidence/hmrc_controller_spec.rb
  spec/factories/hmrc_checks.rb
  spec/helpers/hmrc_check_helper_spec.rb
  spec/helpers/home_helper_spec.rb
  spec/lib/hmrc_income_parser_spec.rb
  spec/models/application_spec.rb
  spec/models/concerns/application_checkable_spec.rb
  spec/models/evidence_check_spec.rb
  spec/models/forms/evidence/hmrc_check_spec.rb
  spec/models/hmrc_check_spec.rb
  spec/models/views/overview/application_spec.rb
  spec/services/evidence_check_selector_spec.rb
  spec/services/hmrc_api_service_spec.rb
  spec/services/hmrc_service_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1842

#1833 RST 6844 - Paper application display Declaration and statement of truth page
  app/controllers/applications/process/benefits_controller.rb
  spec/controllers/applications/process/benefits_controller_spec.rb
  spec/features/applications/benefit_results_are_processed_spec.rb
  spec/features/applications/processing_refund_application_spec.rb
  spec/features/no_evidence_check/rst_1111_spec.rb
  spec/support/admin_application_steps.rb
  spec/support/shared_examples/duplicated_nino.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1833

#1845 ruby update
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1845

#1848 Minor gem fixes
  Gemfile
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1848

#1851 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1851
