Repository hmcts/hwf-staffapp, pull requests merged in 2024-02, with the labels that each got.

#1620 RST-6128 Change income period text content
  charts/help-with-fees-staffapp/Chart.yaml
  config/locales/en.yml
  features/support/page_objects/incomes_page.rb
  spec/models/views/overview/application_spec.rb
  spec/models/views/overview/income_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1620

#1631 RST-6266 Fixing decimal threshold
  app/lib/band_calculation_helper.rb
  spec/lib/band_base_calculation_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1631

#1632 RST-6293 Fixing missing band calculation from HMRC check
  app/models/hmrc_check.rb
  spec/models/hmrc_check_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1632

#1627 RST-6169 Letter template autofill and content
  app/helpers/evidence_check_helper.rb
  app/helpers/expiry_date_format_helper.rb
  app/helpers/income_period_helper.rb
  app/models/views/confirmation/result.rb
  app/views/evidence/return_letter.html.slim
  app/views/evidence_checks/show.html.slim
  app/views/reports/letters.html.slim
  app/views/reports/new_letters.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
  config/locales/en.yml
  config/locales/letters_en.yml
  config/locales/new_letters_en.yml
  config/settings.yml
  spec/helpers/evidence_check_helper_spec.rb
  spec/helpers/income_period_helper_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1627

#1635 RST-6267 password config
  README.md
  config/initializers/devise.rb
  config/locales/en.yml
  spec/factories/users.rb
  spec/features/password_reset_message_spec.rb
  spec/features/user_can_accept_invite_spec.rb
  spec/features/user_profile_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1635

#1633 RST-6034 validation to check none of the above income kind
  app/models/forms/application/income_kind_applicant.rb
  app/models/forms/application/income_kind_partner.rb
  charts/help-with-fees-staffapp/Chart.yaml
  config/locales/en.yml
  spec/models/forms/application/income_kind_applicant_spec.rb
  spec/models/forms/application/income_kind_partner_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1633

#1636 RST-6267 Fixing failing test
  features/step_definitions/nino_evidence_steps.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1636

#1637 Gem update v22
  Gemfile.lock
  config/application.rb
  lib/tasks/raw_data_extract.rake
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1637

#1642 RST-6269 Securing cookies
  config/environments/production.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1642

#1645 RST-6370 Cost of living exception for February 2024
  app/lib/hmrc_cost_of_living.rb
  spec/lib/hmrc_income_parser_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1645

#1644 RST-6259 Checkboxes checked after save and return
  app/controllers/applications/process/details_controller.rb
  app/helpers/income_kind_helper.rb
  app/views/applications/process/income_kind_applicants/index.html.slim
  app/views/applications/process/income_kind_partners/index.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
  spec/controllers/applications/process/details_controller_spec.rb
  spec/helpers/income_kind_helper_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1644
