Repository hmcts/hwf-staffapp, pull requests merged in 2024-04, with the labels that each got.

#1670 RST-6213 create digital raw data report and edic ocmc to allow digital
  app/controllers/report/raw_digital_data_controller.rb
  app/helpers/report_helper.rb
  app/models/views/reports/raw_digital_data_export.rb
  app/views/reports/index.html.slim
  app/views/reports/raw_digital_data.html.slim
  config/routes.rb
  lib/tasks/raw_digital_data_extract.rake
  sonar-project.properties
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1670

#1677 Revert "RST-6213 create digital raw data report and edic ocmc to allow digital"
  app/controllers/report/raw_digital_data_controller.rb
  app/helpers/report_helper.rb
  app/models/views/reports/raw_digital_data_export.rb
  app/views/reports/index.html.slim
  app/views/reports/raw_digital_data.html.slim
  config/routes.rb
  lib/tasks/raw_digital_data_extract.rake
  sonar-project.properties
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1677

#1678 More memory
  charts/help-with-fees-staffapp/Chart.yaml
  charts/help-with-fees-staffapp/values.yaml
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1678

#1673 RST-6391 Fixing evidence check first summary page result
  app/models/views/overview/application.rb
  spec/models/views/overview/application_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1673

#1680 Adding profiling to Sentry
  .rubocop.yml
  Gemfile
  Gemfile.lock
  config/initializers/sentry.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1680

#1682 RST-6390 purge old applications
  README.md
  app/jobs/abandoned_application_purge_job.rb
  spec/jobs/abandoned_application_purge_job_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1682

#1686 RST-6527 Refactoring run.sh to run bg worker
  run.sh
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1686

#1689 Mem tuning Update Chart.yaml
  charts/help-with-fees-staffapp/Chart.yaml
  charts/help-with-fees-staffapp/values.yaml
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1689

#1692 RST-6550 - Fixing HMRC skip check
  app/services/evidence_check_selector.rb
  spec/services/evidence_check_selector_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1692

#1691 RST-6489 Readme update
  .gitignore
  README.md
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1691

#1694 RST-6228 email change and password update
  .env.development.example
  .env.test
  app/controllers/users/passwords_controller.rb
  app/jobs/personal_data_purge_job.rb
  app/mailers/notify_mailer.rb
  config/initializers/devise.rb
  package-lock.json
  package.json
  spec/features/password_reset_message_spec.rb
  spec/jobs/personal_data_purge_job_spec.rb
  spec/mailers/notify_mailer_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1694

#1695 Minor gem updates and refactoring
  .rubocop.yml
  Gemfile.lock
  app/builders/finance_report_builder.rb
  app/builders/finance_transactional_report_builder.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1695
