Repository hmcts/hwf-staffapp, pull requests merged in 2024-10, with the labels that each got.

#1855 RST-6903 - gem updates v40
  Gemfile
  Gemfile.lock
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1855

#1861 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1861

#1863 rst-6802
  app/helpers/result_helper.rb
  app/views/applications/process/confirmation/index.html.slim
  config/locales/new_letters_en.yml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1863

#1864 RST-6898 Date received limit validation added
  app/models/forms/application/fee_status.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1864

#1860 RST-6836 Updating raw data extract
  app/models/views/reports/raw_data_export.rb
  charts/help-with-fees-staffapp/Chart.yaml
  spec/models/views/reports/raw_data_export_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1860

#1866 rst-6905
  app/assets/stylesheets/local/tables.scss
  app/views/feedback/index.html.slim
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1866

#1874 rst-6905 merge error due to required updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1874

#1876 System - gem updates v43
  Gemfile
  Gemfile.lock
  app/models/views/overview/application.rb
  charts/help-with-fees-staffapp/Chart.yaml
  package-lock.json
  package.json
  spec/models/views/overview/application_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1876

#1868 RST-6918 HMRC income for same tax id
  README.md
  app/lib/hmrc_income_parser.rb
  app/models/concerns/hmrc_checkeable.rb
  app/models/evidence_check.rb
  app/models/hmrc_check.rb
  spec/lib/hmrc_income_parser_spec.rb
  spec/models/evidence_check_spec.rb
  spec/models/hmrc_check_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1868

#1879 Test env
  charts/help-with-fees-staffapp/Chart.yaml
  charts/help-with-fees-staffapp/values.yaml
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1879

#1880 Rolling back govuk changes
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1880

#1883 RST-6964 Fixing total income method
  app/models/concerns/hmrc_checkeable.rb
  spec/models/evidence_check_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1883

#1886 RST-6964 HMRC income export
  app/models/evidence_check.rb
  app/models/views/reports/hmrc_ocmc_data_export.rb
  db/migrate/20241024124005_add_hmrc_income_to_evidence_check.rb
  db/schema.rb
  spec/models/evidence_check_spec.rb
  spec/models/views/reports/hmrc_ocmc_data_export_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1886

#1882 RST-6961 GvUk lib update
  charts/help-with-fees-staffapp/Chart.yaml
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1882

#1889 Minor rails update
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1889
