Repository hmcts/hwf-staffapp, pull requests merged in 2024-07, with the labels that each got.

#1775 Minor gem updates
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1775

#1776 RST-6759 email notification
  app/mailers/notify_mailer.rb
  app/models/online_application.rb
  app/services/mail_service.rb
  spec/mailers/notify_mailer_spec.rb
  spec/models/online_application_spec.rb
  spec/services/mail_service_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1776

#1784 Minor gem updates
  Gemfile.lock
  charts/help-with-fees-staffapp/Chart.yaml
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1784

#1779 Rst-6614a Partner ni number added to application details
  app/builders/application_builder.rb
  app/controllers/api/submissions_controller.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1779

#1780 RST-6064 add validation and refactor over_61 to 66
  app/builders/application_builder.rb
  app/controllers/api/submissions_controller.rb
  app/models/applicant.rb
  app/models/forms/application/savings_investment.rb
  app/models/online_application.rb
  app/models/saving.rb
  app/models/views/overview/savings_and_investments.rb
  app/models/views/reports/raw_data_export.rb
  app/services/savings_pass_fail_service.rb
  app/views/applications/process/dependents/_post_ucd.html.slim
  app/views/applications/process/savings_investments/_post_ucd.html.slim
  app/views/applications/process/savings_investments/_pre_ucd.html.slim
  app/views/guide/process_application.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
  config/locales/en.yml
  db/migrate/20240710093713_change_over_61_name.rb
  db/migrate/20240710093812_change_over_61_name_in_savings.rb
  db/migrate/20240710093923_change_partner_over_61_name_in_applications.rb
  db/schema.rb
  features/saving_investments_61.feature
  features/step_definitions/saving_investments_61_steps.rb
  features/support/page_objects/personal_details_page.rb
  spec/builders/application_builder_spec.rb
  spec/controllers/api/submissions_controller_spec.rb
  spec/factories/applicants.rb
  spec/factories/applications.rb
  spec/factories/online_applications.rb
  spec/factories/public_app_submissions.rb
  spec/factories/savings.rb
  spec/features/applications/new_savings_investment_spec.rb
  spec/features/no_evidence_check/rst_975_spec.rb
  spec/lib/income_calculation_spec.rb
  spec/models/applicant_spec.rb
  spec/models/forms/application/savings_investment_spec.rb
  spec/models/hmrc_check_spec.rb
  spec/models/views/overview/applicant_spec.rb
  spec/models/views/reports/raw_data_export_spec.rb
  spec/services/savings_pass_fail_service_spec.rb
  spec/support/admin_application_steps.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1780

#1790 RST-6785 - update rexml to 3.3.2
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1790

#1792 Minor ruby and gem udpates
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1792
