Repository hmcts/hwf-staffapp, pull requests merged in 2025-06, with the labels that each got.

#2124 RST-7331 - Staff guides page banner
  app/views/guide/index.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2124

#2133 RST-7368 Disabling benefit fail redirect
  app/controllers/benefit_overrides_controller.rb
  app/controllers/online_application_benefits_controller.rb
  app/models/forms/online_application.rb
  app/models/views/confirmation/result.rb
  db/migrate/20250604102650_add_dwp_evidence_failed_to_online_application.rb
  db/schema.rb
  features/benefit_checker.feature
  features/step_definitions/benefit_checker_steps.rb
  features/unprocessed_applications_when_dwp_is_down.feature
  spec/controllers/benefit_overrides_controller_spec.rb
  spec/controllers/online_application_benefits_controller_spec.rb
  spec/features/admin_can_manage_the_message_info_spec.rb
  spec/models/forms/online_application_spec.rb
  spec/models/views/confirmation/result_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2133

#2135 Gem updates v18
  .rubocop.yml
  Gemfile.lock
  app/views/layouts/local-template.html.erb
  package.json
  webpack.config.js
  yarn.lock
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2135

#2139 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-2139

#2151 RST-7425 - Frontend reload fix
  app/views/layouts/local-template.html.erb
  config/application.rb
  webpack.config.js
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-2151

#2142 RSt-7361 - Benefit letter template typo fix
  README.md
  config/locales/letters_en.yml
  config/locales/new_letters_en.yml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2142
