Repository hmcts/hwf-staffapp, pull requests merged in 2025-01, with the labels that each got.

#1965 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1965

#1967 Gem updates v6
  .rubocop.yml
  Gemfile.lock
  app/models/views/reports/ocmc_export_helper.rb
  app/models/views/reports/raw_data_export.rb
Labels: ns:help-with-fees, prd:help-with-fees

#1970 rst-7052 Rails update from 7.2 to 8.0
  Gemfile
  Gemfile.lock
  bin/setup
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/puma.rb
  features/support/helpers/datashare_helper.rb
  spec/services/hmrc_api_service_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees

#1979 Don't force expect on params
  .rubocop.yml
Labels: ns:help-with-fees, prd:help-with-fees

#1980 RST-7070 Ruby update
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
  spec/lib/path_storage_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees

#1781 RST-6534 summary pages refactor
  .env.test
  app/controllers/applications/process/savings_investments_controller.rb
  app/controllers/evidence_controller.rb
  app/controllers/part_payments_controller.rb
  app/helpers/processed_views_helper.rb
  app/helpers/section_views_helper.rb
  app/models/applicant.rb
  app/models/concerns/data_field_formattable.rb
  app/models/forms/application/detail.rb
  app/models/views/overview/applicant.rb
  app/models/views/overview/application.rb
  app/models/views/overview/details.rb
  app/models/views/overview/income.rb
  app/models/views/overview/income_helper.rb
  app/models/views/overview/online_application_view.rb
  app/models/views/overview/online_saving.rb
  app/models/views/overview/savings_and_investments.rb
  app/views/applications/process/summary/_post_ucd.html.slim
  app/views/applications/process/summary/index.html.slim
  app/views/evidence/_post_ucd.html.slim
  app/views/evidence/_pre_ucd.html.slim
  app/views/evidence/_summary_post_ucd.html.slim
  app/views/evidence/show.html.slim
  app/views/evidence/summary.html.slim
  app/views/online_applications/_post_ucd_show.html.slim
  app/views/online_applications/_pre_ucd_show.html.slim
  app/views/online_applications/show.html.slim
  app/views/part_payments/_post_ucd.html.slim
  app/views/part_payments/_pre_ucd.html.slim
  app/views/part_payments/_summary_post_ucd.html.slim
  app/views/part_payments/show.html.slim
  app/views/part_payments/summary.html.slim
  app/views/shared/_application_summary.html.slim
  app/views/shared/_remission_type_post_ucd.html.slim
  app/views/shared/_result.html.slim
  app/views/shared/processed_and_deleted/_post_ucd.html.slim
  app/views/shared/processed_and_deleted/_pre_ucd.html.slim
  app/views/shared/processed_and_deleted/_show.html.slim
  config/locales/en.yml
  spec/controllers/applications/process/savings_investments_controller_spec.rb
  spec/factories/applicants.rb
  spec/features/evidence-checks/evidence_check_page_displayed_instead_of_confirmation_spec.rb
  spec/features/evidence-checks/evidence_check_part_payment_flow_spec.rb
  spec/models/forms/application/applicant_spec.rb
  spec/models/forms/application/detail_spec.rb
  spec/models/views/overview/application_spec.rb
  spec/models/views/overview/details_spec.rb
  spec/models/views/overview/online_application_view_spec.rb
  spec/models/views/overview/online_saving_spec.rb
  spec/models/views/overview/savings_and_investments_spec.rb
  spec/models/views/reports/raw_data_export_spec.rb
  spec/services/hmrc_api_service_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1781

#1984 RST-7111 - Fixing nil issue with under 16 and kids section
  app/models/views/overview/online_application_view.rb
  app/views/online_applications/_post_ucd_show.html.slim
  spec/models/views/overview/online_application_view_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees

#1690 RST-5658 - fix negative fee error
  README.md
  app/models/forms/online_application.rb
  config/locales/en.yml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1690

#1983 RST-7058 - Removing partner info
  app/views/online_applications/edit.html.slim
  spec/features/online_applications/staff_can_add_details_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm

#1981 RST-7098 Updated GovUK Frontend to 5.8.0
  app/assets/stylesheets/application.scss
  charts/help-with-fees-staffapp/Chart.yaml
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm
