Repository hmcts/hwf-staffapp, pull requests merged in 2025-02, with the labels that each got.

#1995 RST-7126 Removing middleware use of ApplicationInsights
  config/application.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1995

#1994 RST-7116 - Remove Partner NI hint text
  app/views/applications/process/partner_informations/index.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-1994

#1996 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1996

#2001 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-2001

#1992 7014 fire wall on special characters instead of validation
  app/views/applications/process/details/index.html.slim
  app/views/applications/process/incomes/index.html.slim
  app/views/applications/process/partner_informations/index.html.slim
  app/views/applications/process/personal_informations/index.html.slim
  app/views/applications/process/representative/index.html.slim
  app/views/home/index.html.slim
  app/views/online_applications/edit.html.slim
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-1992

#2009 Gem updates v5
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
  app/models/views/application_list.rb
  app/models/views/application_result.rb
  app/models/views/confirmation/result.rb
  app/models/views/overview/application.rb
  app/models/views/overview/online_applicant.rb
  app/models/views/overview/online_application_view.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-2009

#2014 RST-7158 - Only show representative details when present
  app/views/shared/_application_summary.html.slim
  app/views/shared/_notifications.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2014

#2004 RST-7092 - No partner details where no Applicant NI number
  app/controllers/applications/process/personal_informations_controller.rb
  app/models/applicant.rb
  app/views/online_applications/_post_ucd_show.html.slim
  app/views/shared/_application_summary.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
  spec/models/forms/application/partner_spec.rb
  spec/models/views/reports/hmrc_ocmc_data_export_spec.rb
  spec/models/views/reports/raw_data_export_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2004

#2019 Remove text type on input field and keep number type
  Gemfile.lock
  app/views/shared/savings/_amount.slim
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-2019

#2013 RST-6959 - Replaced CKEditor with ActionText's Trix
  Dockerfile
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/ckeditor/config.js
  app/assets/stylesheets/actiontext.css
  app/assets/stylesheets/application.scss
  app/models/notification.rb
  app/views/active_storage/blobs/_blob.html.erb
  app/views/layouts/action_text/contents/_content.html.erb
  app/views/notifications/_form.html.slim
  app/views/notifications/edit.html.slim
  app/views/shared/_notifications.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
  config/importmap.rb
  config/initializers/assets.rb
  config/initializers/ckeditor.rb
  db/migrate/20250217094406_create_action_text_tables.action_text.rb
  db/schema.rb
  features/step_definitions/notification_banner_steps.rb
  features/support/page_objects/edit_banner_page.rb
  package.json
  spec/features/admin_can_manage_the_message_info_spec.rb
  yarn.lock
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2013

#2021 RSt-7169 Fixing savings on summary page
  app/models/views/overview/online_saving.rb
  app/models/views/overview/savings_and_investments.rb
  app/views/online_applications/_post_ucd_show.html.slim
  app/views/shared/_application_summary.html.slim
  spec/models/views/overview/online_saving_spec.rb
  spec/models/views/overview/savings_and_investments_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-2021

#2026 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2026

#2024 RST 7159 Change date received limit from 2 to 3 years and edit the error message
  app/models/forms/application/fee_status.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2024

#2027 RST-7061 Reordering summary log
  app/views/shared/_processed_summary.html.slim
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2027
