Repository hmcts/hwf-staffapp, pull requests merged in 2025-05, with the labels that each got.

#2090 RST-7265 - Applications by Court fields update
  Gemfile
  Gemfile.lock
  app/models/views/reports/hmrc_ocmc_data_export.rb
  charts/help-with-fees-staffapp/Chart.yaml
  features/savings_investments.feature
  features/step_definitions/process_online_application_steps.rb
  features/step_definitions/savings_investments_steps.rb
  features/support/capybara_driver_helper.rb
  features/support/env.rb
  features/support/saucelabs/browsers.yml
  spec/models/views/reports/datashare_export_spec.rb
  spec/models/views/reports/hmrc_ocmc_data_export_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-2090

#2093 RST-7258 error message when dob same as date received
  Gemfile
  Gemfile.lock
  app/models/forms/application/applicant.rb
  app/views/applications/process/personal_informations/index.html.slim
  config/locales/en.yml
  spec/factories/personal_information.rb
  spec/models/forms/application/applicant_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2093

#2102 RST-7280 Minimal fee 3
  app/models/forms/application/detail.rb
  app/models/forms/online_application.rb
  config/locales/en.yml
  spec/models/forms/application/detail_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2102

#2105 RST-7273 - Types of income validation
  app/models/forms/application/income_kind_applicant.rb
  app/views/applications/process/income_kind_applicants/index.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
  config/locales/en.yml
  spec/models/forms/application/income_kind_applicant_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2105

#2113 RST-7337 - Logging benefit check calls
  app/services/benefit_check_runner.rb
  app/services/online_benefit_check_runner.rb
  spec/services/benefit_check_runner_spec.rb
  spec/services/online_benefit_check_runner_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-2113

#2114 RST-7338 No benefits check for no answer when digital
  app/services/benefit_check_runner.rb
  spec/services/benefit_check_runner_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-2114

#2116 Rst-7347 benefit override report
  app/models/views/reports/hmrc_ocmc_data_export.rb
  app/models/views/reports/raw_data_export.rb
  spec/models/views/reports/hmrc_ocmc_data_export_spec.rb
  spec/models/views/reports/raw_data_export_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-staffapp-pr-2116

#2121 RST-7352 - Applications by court update
  app/controllers/report/ocmc_controller.rb
  app/controllers/reports_controller.rb
  app/jobs/ocmc_export_job.rb
  app/models/forms/finance_report.rb
  app/models/views/reports/hmrc_ocmc_data_export.rb
  app/models/views/reports/ocmc_export_helper.rb
  app/views/reports/ocmc_report.html.slim
  app/views/reports/raw_data.html.slim
  app/views/shared/_report_by_court.html.slim
  charts/help-with-fees-staffapp/Chart.yaml
  config/locales/en.yml
  spec/controllers/report/ocmc_controller_spec.rb
  spec/jobs/ocmc_export_job_spec.rb
  spec/models/views/reports/datashare_export_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-staffapp-pr-2121
